### ISSUE TITLE
Support for sqlcipher

### ISSUE THREAD

**Issue by nikgraf** [ospfranco/react-native-quick-sqlite#10]
Would you consider adding support for sqlcipher?

For the other projects there are forks, but would be great to have it in a lib that actively supports it.

My resource so far:

- https://github.com/andpor/react-native-sqlite-storage
  - Fork: this seems to be the best https://github.com/linchenhuicn/react-native-sqlcipher
  - Fork: https://github.com/axsy-dev/react-native-sqlcipher-storage
- https://github.com/craftzdog/react-native-sqlite-2
  - Fork: https://github.com/sreejithkrishnanr/react-native-sqlcipher-2

**Comment by ospfranco** [comment]
I have no idea how to enable or do SQLCipher :)

PRs are more than welcome though, will gladly review and merge any contribution

**Comment by ospfranco** [comment]
Ok, I've read a bit and SQLCipher is a fork of SQLite right? well... to be honest, I learned the bare minimum to get SQLite running, so TBH I will not really spend my time adding support for a fork

That being said, someone already asked for encryption support, so I can see it is valuable, so if you or someone else decides to give it a go, I will gladly support the integration effort

On the other hand, I would also like to keep the possibility to use pure SQLite, so if someone manages to modify the compilation chain to use the SQLite amalgamation OR SQLCipher, that would be the solution I would like the most

**Comment by ospfranco** [comment]
After thinking about this a bit more, tbh, I won't support a sqlite branch, I barely maintain the current package as it is, therefore I think it is better to fork the repo if you want another sqlite version supported
