### ISSUE TITLE
Does this library support database versions?

### ISSUE THREAD

**Issue by migueldaipre** [ospfranco/react-native-quick-sqlite#101]
### Why ?

I would like to create a migration system, where I would need to check the previous version of the database.

Code Example : https://codeburst.io/react-native-sqlite-and-migrations-bc72b70e66fb

It is possible ?

I couldn't find anything about database versions and I also don't see the database in Android Studio's App Inspector.

**Comment by ospfranco** [comment]
This library is mostly a low level driver, the article you posted deals by setting a user_version variable which you can do with a simple sql query. Anything other than that you have to handle yourself.
