### ISSUE TITLE
error: database name must be a string

### ISSUE THREAD

**Issue by agatiwi** [ospfranco/react-native-quick-sqlite#106]
I have weird problem 
My app is in react-native: "0.70.6"
The database "plantsSQLite.db" is prepopulated and I have tried to put it in many different locations 
Any ideas what could be wrong?

````
import { open } from 'react-native-quick-sqlite';

const Plants = ({navigation}) => {
  React.useEffect(() => {
    try {
      let databaseName = "plantsSQLite.db";
      const db = open(databaseName);
    } catch (e) {
      console.error('Something went wrong executing SQL commands:', e.message);
    }
    }, [])
  return (null);
};
```

**Comment by ospfranco** [comment]
See similar issues:

https://github.com/ospfranco/react-native-quick-sqlite/issues/66
https://github.com/ospfranco/react-native-quick-sqlite/issues/68

As well as the instructions in the [README regarding the database location](https://github.com/ospfranco/react-native-quick-sqlite#loading-existing-dbs).

**Comment by agatiwi** [comment]
I have read what you linked - thank you
Unfortunately, I have a problem understanding what is the default location for DB 
I guess that there is a Document directory mentioned, but I don't actually see it in my project - could you tell me something more about how to find the default directory?

I have seen that you linked this
https://github.com/ospfranco/react-native-quick-sqlite/blob/main/android/src/main/java/com/reactnativequicksqlite/QuickSQLiteBridge.java#L16 
I am afraid that my Java knowledge is not as great tho, and I have a problem finding online what can i do, to check what location will this line return

**Comment by ospfranco** [comment]
Please ask StackOverflow. The document path will change depending on Android versions/vendors and what not. You will need to use one of the many rn-fs packages to move files around on runtime.

**Comment by agatiwi** [comment]
for those who may be interested

the solution was: 

database file must be in directory: 

> YourAwesomeReactNativeProject/android/app/src/main/assets/www/database_name.db

finally my code works being like that:
```
import { open } from 'react-native-quick-sqlite';

let db = SQLite.openDatabase({
  name: 'database_name.db',
  createFromLocation: 1,
});

const Plants = ({navigation}) => {
  const [otherData, setOtherData] = useState({});
  const [name, setName] = useState({});

  const fetchData = async () => {
    try {
      let pid = {pid: []};
      let another = {
        language: [],
        origin: [],
    };
    await db.transaction(txn => {
        txn.executeSql(
          `SELECT pid, language, origin FROM 'table_name'`,
          [],
          (tx, res) => {
            console.log('Query completed');
            });});
      });
    } catch (e) {
      console.log(e);
    }};

  useEffect(() => {
    fetchData();
  }, []);
```

**Comment by ospfranco** [comment]
Where did you get `createFromLocation: 1` from? That param does not exist. Also putting in the assets folder should not work either. You probably have a copy floating around from a previous attempts and that makes it look like it is working.
