### ISSUE TITLE
RN 0.71 support

### ISSUE THREAD

**Issue by billnbell** [ospfranco/react-native-quick-sqlite#107]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bill/theclub/TheClub/node_modules/react-native-quick-sqlite/android/build.gradle' line: 201

* What went wrong:
A problem occurred evaluating project ':react-native-quick-sqlite'.
> Expected directory '/Users/bill/theclub/TheClub/node_modules/react-native/android' to contain exactly one file, however, it contains no files.

**Comment by billnbell** [comment]
def rnAAR = fileTree("$reactNative/android").matching({ it.include rnAarMatcher }).singleFile

The dir has README.md and it is not seen that

**Comment by ErHarinderSingh** [comment]
Same issue here @ospfranco :)

**Comment by ospfranco** [comment]
haha LOL

```
/Users/osp/Developer/quick_sqlite_test/node_modules/react-native/android
cat README.md
# The `/android` folder inside `react-native`

Starting from React Native 0.71, we're not shipping the `/android` folder inside the React Native NPM package
anymore due to sizing constraints on NPM. The Android artifacts are distributed via Maven Central.
You can read more about it in this RFC:
https://github.com/react-native-community/discussions-and-proposals/pull/508

If you're a library author and you're manipulating the React Native .aar files, to extract headers,
extract `.so` files or do anything with it, you're probably doing something wrong. React Native
0.71 ships with all the necessary logic to let you consume it transparently by just using:

```
implementation("com.facebook.react:react-android")
// or to keep backward compatibility with older versions of React Native:
implementation("com.facebook.react:react-native:+")
```

You should consider refactoring your library code not to unzip/manipulate the React Native .aar files.

This README.md file is kept in this folder as some libraries are checking the existence of the `/android` folder
and failing user builds if the folder is missing.
```

Time to dive deep into RN C++ code... this might take a while

**Comment by billnbell** [comment]
Any thoughts on a fix?

**Comment by billnbell** [comment]
Another package did the following:

https://github.com/mrousavy/react-native-vision-camera/pull/1438/commits/1d26bb6c3955dc8f4106d1857fbc0601d38ba898

**Comment by ospfranco** [comment]
@billnbell there is already a version that supports 0.71: 8.0.0-beta1

**Comment by billnbell** [comment]
what is a link to get that?

**Comment by ospfranco** [comment]
you can just declare that on your package.json

**Comment by billnbell** [comment]
yeah but I want to review the code. Is the a Git repo for it?

**Comment by ospfranco** [comment]
https://github.com/ospfranco/react-native-quick-sqlite/pull/108
