### ISSUE TITLE
Feature request: support BLOBs?

### ISSUE THREAD

**Issue by andymatuschak** [ospfranco/react-native-quick-sqlite#11]
I wonder if you'd be willing to add support for BLOB-typed columns, e.g. by bridging to `ArrayBuffer`?

See e.g. how `react-native-leveldb` implemented support for no-copy binary data: https://github.com/greentriangle/react-native-leveldb/blob/master/cpp/react-native-leveldb.cpp

**Comment by ospfranco** [comment]
PRs are welcome, since you already have the JSI code, you might only need to adjust it for the SQLite response
