### ISSUE TITLE
custom functions supported?

### ISSUE THREAD

**Issue by Mythli** [ospfranco/react-native-quick-sqlite#114]
Dear community,

I could not find this in the documentation so I'm guessing at this point, custom sqlite functions are not supported.

As a developer I would like to define custom javascript functions much like I can with better-sqlite3 in nodejs.

https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#functionname-options-function---this

Is there any plan to add this in the future?

If yes, I can see my company sponsoring the development of this functionality financially.
I'm unfortunately not skilled enough to do it myself.

Best regards
Tobias

**Comment by ospfranco** [comment]
Hi Tobias, never saw this functionality before but anything is possible. Feel free to write me an email to ospfranco@protonmail.com to discuss any possibilities.

**Comment by Mythli** [comment]
Hi!

I dropped you a mail from tobias@butlerapp.de. Have you got it?

Maybe it went into your spam folder. 

Could you kindly check and get back to me?

Best regards
Tobias

**Comment by ospfranco** [comment]
If this is something that is still needed and you are willing to pay for development, please open a ticket on the new library: [op-sqlite](https://github.com/OP-Engineering/op-sqlite)
