### ISSUE TITLE
USE_HERMES is not properly defined in 8.0.0-beta 

### ISSUE THREAD

**Issue by only1chi** [ospfranco/react-native-quick-sqlite#117]
In the build.gradle file, the parameter `USE_HERMES` is not properly defined when your application uses: 
- `react-native-quick-sqlite@^8.0.0-beta.2`
- `react-native@0.71.2`
- `newArchEnabled=false`
- `hermesEnabled=true` 

In the build.gradle file, USE_HERMES is defined as follows:
```
 if (findProject(":app")) {
  def appProjectExt = project(":app").ext
  USE_HERMES = project(":app").ext.react.enableHermes
}
```

The result is that `USE_HERMES` evaluates to `null`, and the application will fail to load library `libjscexecutor.so`.

The resulting error is something like this:
```
Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjscexecutor.so" not found: needed by /data/app/~~ByTFORh9q085U5eASAL97g==/com.ststorquefit-NoDVUQtszoKXFDrf9CwX3w==/base.apk!/lib/arm64-v8a/libreact-native-quick-sqlite.so in namespace classloader-namespace, js engine: hermes
```

To fix it, the build.gradle file should correctly define USE_HERMES as follows:
```
 if (findProject(":app")) {
  def appProjectExt = project(":app").ext
  USE_HERMES = rootProject.ext.hermesEnabled
}
```

**Comment by ospfranco** [comment]
The latest version is 8.0.0 without any beta prefix, try updating and also clearing your gralde build

**Comment by only1chi** [comment]
> The latest version is 8.0.0 without any beta prefix, try updating and also clearing your gralde build

Hi @ospfranco,
I just checked but there's no npm package for react-native-quick-sqlite version 8.0.0 without the beta prefix.

**Comment by ospfranco** [comment]
weird, I remember getting the email, but I ran it again and it should be published.

**Comment by Absor** [comment]
@ospfranco  I have this same problem, current value https://github.com/ospfranco/react-native-quick-sqlite/blob/4d21bb62ba1af85a5835c11c6e637ff58f599991/android/build.gradle#L46 is not like @only1chi suggested.
At least `enableHermes` should probably be `hermesEnabled` to match the variable name, probably needs the rootProject change also.

The resulting error from current version is
```
Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjscexecutor.so" not found: needed by /data/app/~~A3n2h-pBy3UZ0qeamO0eeg==/fi.fingrid.fingridapps-HrLVRlUb-ZavMetS7VmppQ==/lib/arm64/libreact-native-quick-sqlite.so in namespace classloader-namespace, js engine: hermes
```

**Comment by Absor** [comment]
Tried changing this manually to verify and this worked without errors:
```
def USE_HERMES = false

if (findProject(":app")) {
  USE_HERMES = rootProject.ext.hermesEnabled
} 
```

**Comment by ospfranco** [comment]
ah, thanks for noticing, weird it was working in my tests. I will take a look later

**Comment by only1chi** [comment]
> At least `enableHermes` should probably be `hermesEnabled` to match the variable name, probably needs the rootProject change also.

Yes you do need the rootProject change to correctly reference the property, which is `hermesEnabled` and NOT `enableHermes`.

**Comment by ospfranco** [comment]
Are you sure you guys are using the default `build.gradle`? I just took a look at another project of mine and `enableHermes` is correct name

**Comment by only1chi** [comment]
> Are you sure you guys are using the default `build.gradle`? I just took a look at another project of mine and `enableHermes` is correct name

With react-native 0.71, we no longer use `project.ext.react.enableHermes`. This is now deprecated.
What are you referring to as the default `build.gradle`?

**Comment by ospfranco** [comment]
The default created by `npx react-native init` shows that the value on the gradle.properties is called ``hermesEnabled`. So yeah, you guys are right.

**Comment by Absor** [comment]
It doesn't seem to work without the rootProject.

For example the current
```
project(":app").ext.react.hermesEnabled
```
doesn't work but
```
rootProject.ext.hermesEnabled
```
works.

**Comment by ospfranco** [comment]
try again please `8.0.2`

**Comment by Absor** [comment]
`8.0.2` works! Thanks! I did npm clean install and gradlew clean to be sure and no more errors.

**Comment by only1chi** [comment]
Thank you @ospfranco and @Absor.
