### ISSUE TITLE
android build failed with expo 48 and react native 0.71.3

### ISSUE THREAD

**Issue by meabed** [ospfranco/react-native-quick-sqlite#118]
When building with expo 48 and react native 0.71.3 build failed with 

* Where:
Build file '/node_modules/react-native-quick-sqlite/android/build.gradle' line: 42

* What went wrong:
A problem occurred evaluating project ':react-native-quick-sqlite'.
> Cannot get property 'hermesEnabled' on extra properties extension as it does not exist

Looking at expo hermsEnabled looks like this: 

```
# app/build.gradle

// Override `hermesEnabled` by `expo.jsEngine`
ext {
  hermesEnabled = (findProperty('expo.jsEngine') ?: "hermes") == "hermes"
}



dependencies {
  if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}


# MainApplication.java

      @Override
      protected Boolean isHermesEnabled() {
        return BuildConfig.IS_HERMES_ENABLED;
      }

```

**Comment by ospfranco** [comment]
I care little for expo, they have their own sqlite package which I believe they will migrate to JSI. You are better off sticking to that.

**Comment by meabed** [comment]
Thank you, I understand, It would be great to fix, if its not big effort. if not that totally fine :) appreciate your response.

**Comment by ospfranco** [comment]
Sorry no time and I also don't use expo. Since they have their own package it makes little sense to do the extra work for them :)

**Comment by grantmagdanz** [comment]
@meabed how are you running this with expo? Did you find a workaround? I'm trying to install this library in an expo app.
