### ISSUE TITLE
Transaction support?

### ISSUE THREAD

**Issue by nikgraf** [ospfranco/react-native-quick-sqlite#13]
I was checking out the API, but seems like transactions are not supported. Do you have plans to add them?

**Comment by z0al** [comment]
Is the new `executeSqlBatch` equivalent  transactions?

**Comment by ospfranco** [comment]
yes, internally it is using transactions

**Comment by ospfranco** [comment]
Time to stop being lazy and implement transactions for real. Anyone has any idea how to do it? 😁 the ones from sqlite-storage look mighty complex.

**Comment by ospfranco** [comment]
@EduFrazao the executeSqlBatch does everything on the native side, but a generic callback on the javascript makes sense right?

**Comment by EduFrazao** [comment]
> executeSqlBatch

Today, executeSqlBatch dispatch a bunch of commands inside a implicit transaction, and returns the status and affected rows. Its async counterpart does the same thing in another thread and invokes a callback do dispatch the result.

What is your idea about a generic callback? I think I don't get the idea.

About a transaction API, I have some doubts too:

 -- Maybe a transacion object with a mutex lock? This transaction object must be served inside a method invocation (callback), so we can know when the work is finshed and can commit (or rollback) and release the mutex.
 
 -- How to implement this transaction API in a async way? Maybe invoking the callback (on the JS Thread) to collect all the SQL commands and put them inside a vector to dispatch everything? This will work, but only for update querys, and this lead us to another question:
 -- How can we support select statements inside the transacion scope and isolation to allow users to change their transaction logic based on this results?

**Comment by ospfranco** [comment]
This is what react-native-sqlite-storage (and other packages) offer for transactions:

<img width="826" alt="Screenshot 000328" src="https://user-images.githubusercontent.com/1634213/166114815-b4628aa8-cf98-4e81-b288-2b6637baa2fa.png">

I know that executeSqlBatch does the internal transaction, but it's non-standard from what I see. You might also want to do javascript logic inside of a transaction(? or not? not really sure), so having javascript access inside of the block might be useful.

- Yes, a mutex-like mechanisms are implemented in other libraries [here is the link to sqlite-storage again](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js?rgh-link-date=2021-10-21T11%3A17%3A52Z#L134)
- If all the work is inside of a callback then it's not really a problem of executing the function body in an async manner, right?
- Didn't think of this, would it really be an issue?

**Comment by EduFrazao** [comment]
> This is what react-native-sqlite-storage (and other packages) offer for transactions:
> 
> <img alt="Screenshot 000328" width="826" src="https://user-images.githubusercontent.com/1634213/166114815-b4628aa8-cf98-4e81-b288-2b6637baa2fa.png">
> 
> I know that executeSqlBatch does the internal transaction, but it's non-standard from what I see. You might also want to do javascript logic inside of a transaction(? or not? not really sure), so having javascript access inside of the block might be useful.
> 
> * Yes, a mutex-like mechanisms are implemented in other libraries [here is the link to sqlite-storage again](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js?rgh-link-date=2021-10-21T11%3A17%3A52Z#L134)
> * If all the work is inside of a callback then it's not really a problem of executing the function body in an async manner, right?
> * Didn't think of this, would it really be an issue?

I think that the only benefit of having transaction support in the JavaScript side (besides the more semantic code) is to able to collect data from the transaction context, that is somehow impossible today. If you run a statement, that fires a trigger that changes anything, you will not be able to fetch this data inside the transaction scope and even rollback based of this data for example. So yes, I think that its a very nice low level api feature :).

Execute the whole body in a async fashion may be challenge, because we need to translate the parans inside the JavaScript thread, execute SQL commands in another thread, and then convert the results to JavaScript objects in the JS thread again to deliver it to the JavaScript API.

I don't know if this can be done keeping a sane transaction block using everything async.
For example:

```typescript
db.transaction((tx) => {
    tx.executeSQL('insert into x values (?)', [1], (_tx, res) => {
        // To be able to get "res" object on this callback this execution must be dispatched first to the invokeAsync of the jsCallInvoker to translate data, and at this point, as this will be deffered, we can already closed the transaction code, because we cannot (I think) wait fot the invokeAsync conclusion).
        
      // Selecting some data of table Y after a trigger of X alter it.
      tx.executeSQL('select * from x', [], (_tx, res) => {
         // Again, this code can only be executed in a invokeAsync c++ callback.
          if(res.rows.item(0).value > 10) { 
             tx.executeSQL('DELETE FROM Z where ID = ?', [res.rows.item(0).someColumn]);
           } else {
             tx.rollback();
           }
      });
    });
   // How can we know that is safe to commit the transaction here, if we can't ensure that nested executeSQL callbacks have concluded their work? Maybe track them somehow? Its a very cool problem :)
});

```

With the synchronized API this can be done of course, but we will have the performance problems that we are aware of, in large transactions.

**Comment by ospfranco** [comment]
I do understand that you have very large transactions, but I believe you are in the minority here, and you can always fallback to the existing async methods. Whereas this is generally applicable to most apps I believe. So I would go for it.

**Comment by EduFrazao** [comment]
> I do understand that you have very large transactions, but I believe you are in the minority here, and you can always fallback to the existing async methods. Whereas this is generally applicable to most apps I believe. So I would go for it.

Sure.. Do you want to start the work for a synchronized transaction support, and later try to work on the async counterpart? I will like to contribute of course :)

**Comment by ospfranco** [comment]
yeah, I would like to give it a try. But I'm not sure where/how to start. The sqlite-storage approach looks simple(ish) on the surface... I'll try to replicate it and see how far I get

**Comment by EduFrazao** [comment]
> yeah, I would like to give it a try. But I'm not sure where/how to start. The sqlite-storage approach looks simple(ish) on the surface... I'll try to replicate it and see how far I get

I think that its a good start, even more because this library aims to be sqlite-storage compatible.
Do you think that we can enhance the API keeping the it compatible, like inserting a silent rollback method?
And what about the mutexes? Maybe share a single instance of it for any sql execution, as now we have async work being done on the same sqlite3 object in different threads?

**Comment by ospfranco** [comment]
- I haven't taken a look into rollbacks yet, but can you explain a bit what do you mean?
- sqlite-storage has per db mutex, I think that makes sense

**Comment by EduFrazao** [comment]
> * I haven't taken a look into rollbacks yet, but can you explain a bit what do you mean?
> * sqlite-storage has per db mutex, I think that makes sense

Its only a API to request a silent rollback on the transaction callback code. But you already done that, asking for a boolean return to commit or not the API. :)
Thanks!
