### ISSUE TITLE
Integer Overflow During Type Conversions

### ISSUE THREAD

**Issue by vinnybad** [ospfranco/react-native-quick-sqlite#16]
I encountered an integer overflow for `INTEGER(8)` (8-byte ints) during type conversions. Here's a code sample showing the error: 

```js
async function reproError() {
  try {
    const connection = await openDb('reproBug.sqlite', './');
    if (!connection) {
      throw new Error('Cannot get a connection to reproBug.sqlite');
    }

    const createSql = `CREATE TABLE IF NOT EXISTS "foo" (
      "created" integer(8) NOT NULL DEFAULT(1)
    );`;
    let res = await executeSql(connection, createSql, []);
    console.log(`createTable result: ${JSON.stringify(res, null, 2)}`);

    const insertSql = 'INSERT INTO foo (created) VALUES (1588399753901)';
    await executeSql(connection, insertSql, []);

    res = await executeSql(connection, 'SELECT * FROM foo', []);
    console.log(`Number of rows: ${res.rows.length}`);
    let item = res.rows.item(0);

    // Verify the value for created seems to have underflowed
    console.log(`Found item: ${JSON.stringify(item, null, 2)}`);

    res = await executeSql(
      connection,
      'SELECT *, CAST(created as TEXT) AS createdStr FROM foo ',
      [],
    );
    console.log(`Number of rows: ${res.rows.length}`);
    item = res.rows.item(0);

    // Verify the value is properly stored in sqlite by converting the value to a string and sending it over
    console.log(`Found item: ${JSON.stringify(item, null, 2)}`);
  } catch (error) {
    console.error(
      'Encountered an error when trying to repro the error. Details:',
      error,
    );
  }
}
```

For the functions `executeSql` and `openDb`: they are promise versions of the functions that exist in react-native-quick-sqlite:

```js
async function openDb(name: string, location: string) {
  return new Promise<DBConnection>((resolve, reject) => {
    openDatabase(
      {
        name,
        location,
      },
      resolve,
      reject,
    );
  });
}

async function executeSql(
  connection: DBConnection,
  sql: string,
  args: any[],
): Promise<OkResponse> {
  return new Promise((resolve, reject) => {
    connection.executeSql(sql, args, resolve, reject);
  });
}
```

The output of `reproError` is: 

```
 LOG  createTable result: {
  "rows": {
    "status": 0,
    "length": 0,
    "_array": []
  },
  "rowsAffected": 0
}
 LOG  Number of rows: 9
 LOG  Found item: {
  "created": -738145619
}
 LOG  Number of rows: 9
 LOG  Found item: {
  "created": -738145619,
  "createdStr": "1588399753901"
}
```

So the value `1588399753901` can be inserted properly in sqlite in INTEGER(8) form, but when retrieving, there is integer overflow. Converting it to TEXT in sqlite before retrieval gets the proper value, but it would be nice to not have to have additional string conversions, just to re-parse as numbers on the JS side...

Any ideas on how to fix this?

**Comment by vinnybad** [comment]
I see it happens here: https://github.com/ospfranco/react-native-quick-sqlite/blob/main/cpp/sequel.cpp#L309

We're using `sqlite3_column_int`, which is for a 32-bit int. Any objections to changing it to a 64 bit int? 

Some options: 
* Option 1: Keep the status quo (requires string conversion and parsing on client -- not ideal)
* Option 2: Detect the size of data somehow and use `sqlite3_column_int` or `sqlite3_column_int64`. This is ideal, but [this thread](https://stackoverflow.com/a/13835219/190713) indicates that sqlite3 handles values internally as `int64` and truncates values if it's requested as an `int32`...
* Option 3: Always use 64-bit ints. 

Given the [above mentioned thread](https://stackoverflow.com/a/13835219/190713), I think we should go forward with this.

**Comment by ospfranco** [comment]
I'm not sure I completely understand the change but it sounds dangerous, since javascript stores all numbers as 64 bit floats, I would gladly merge the PR, but only if there are tests that verify that nothing breaks

**Comment by vinnybad** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates

> In JavaScript, numbers are implemented in double-precision 64-bit binary format IEEE 754 (i.e., a number between ±2^−1022 and ±2^+1023, or about ±10^−308 to ±10^+308, with a numeric precision of 53 bits). Integer values up to ±2^53 − 1 can be represented exactly.

in short, we can only represent 53-but integers in JS. All numbers are represented this way, including the int32 that’s being sent today. 

Enabling this change only increases the possible range of representable numbers when selecting information and does not introduce risk.

**Comment by ospfranco** [comment]
[sqlite-storage seems to be using int64 here](https://github.com/andpor/react-native-sqlite-storage/blob/master/platforms/ios/SQLite.m#L536)

The problem I see is that you are assuming that all the databases that you might feed into the package are going to come from this library and JS, casting an int as double might throw garbage if you try to load a sqlite3 database where the bytes are truly meant to represent 64 bit ints... but in that case, there I guess there is no good way to transfer that data to JS

In any case, I'm not comfortable casing an int to a double, and would rather do the same as sqlite-storage and use a int64

if you update your PR and add a comment clarifying the pitfall (both in code and in readme) I will merge it right away and publish a new version

**Comment by vinnybad** [comment]
@ospfranco there is no way to send a `int64_t` in a `js::Value`. Changing the `double` to an `int64_t` leads to a compile error because there's no constructor in `js::Value` that accepts an `int64_t`.

**Comment by vinnybad** [comment]
@ospfranco -- cool, I've updated the PR. Thanks!
