### ISSUE TITLE
Implement storage engine for redux-persist on top of this library

### ISSUE THREAD

**Issue by dimaportenko** [ospfranco/react-native-quick-sqlite#2]
I believe a lot of people use redux-persis. This library can give a huge performance boost for many projects and blow up popularity for this lib.

Looking into this https://github.com/prsn/redux-persist-sqlite-storage it shouldn't be so hard. I'm going to try to do it myself, but I don't really familiar with SQLite. @ospfranco let me know if you like to collaborate on it.

**Comment by ospfranco** [comment]
I thought about this when creating the library but never found sense it trying to cram json data into a sqlite db.

Relational data is not **really** compatible with simple key:value structures, you could try to raw store the string inside of sqlite rows (which is what sqlite-storage does), but then question is... what's the benefit? transactions? you will definitely not get a speed bump over simple disk write/read even with JSI

You are better off using key:value solutions which take advantage of the JSI bridge, such as [mmkv-storage](https://github.com/ammarahm-ed/react-native-mmkv-storage)

TBH feel free to fork the library or create your work on top of it, but it's not something I'm really interested in

**Comment by dimaportenko** [comment]
Yeah, totally makes sense for me. Thank you for your feedback. I'll take a closer look on [mmkv-storage](https://github.com/ammarahm-ed/react-native-mmkv-storage)
