### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by HenrikZabel** [ospfranco/react-native-quick-sqlite#20]
After failing to install WatermelonDB, realm or using react-native-mmkv I wanted to start using react-native-quick-sqlite because I hope it'll be faster than every other sql library for react native out there. But when I wanted to start I searched for the Docs. Are there any docs? And if yes where can I find them. Docs would be really helpful haha

**Comment by ospfranco** [comment]
The readme is all the docs you need, there is nothing more to it, this module is quite low-level on it's won, but if you read the README it is recommended to use TypeORM (also with instructions in the README)
