### ISSUE TITLE
Support for SQLite Compile-Time Options?

### ISSUE THREAD

**Issue by HaydenPWoods** [ospfranco/react-native-quick-sqlite#37]
Looking at this library as a replacement for react-native-sqlite-storage in a project I'm working on and first impressions are great. 

I've got requirements for enabling FTS5 and Geopoly extensions. This seems possible with this library as opposed to RNSS since the SQLite source is compiled from /cpp for both iOS and Android, instead of using the phone's SQLite. Is there any method of setting compile-time options for enabling specific extensions (e.g. SQLITE_ENABLE_GEOPOLY) ?

The closest I have reached is presuming that you can set options somewhere in 'CMakeLists.txt' for Android and the podspec for iOS, but I've not been having any luck.

Thanks.

**Comment by ospfranco** [comment]
That's an interesting use case, but no, I have never tried modifying the compilation behavior of the embedded SQLite source.

Indeed you can try setting flags on the CMakeLists and for iOS I would assume you need to set them somewhere on the XCode build settings.

**Comment by ospfranco** [comment]
Arent those flags global though? You can try first setting them globally in your environment to see if that works. Then try to figure out how to enable them in a specific project only.

**Comment by HaydenPWoods** [comment]
Thanks for the quick reply, and happy to hear that you think it's a possibility at least. I didn't know that these flags could be set globally, so I'll give that a shot to see if I can add any extensions at all. Global flags might be good enough for me for now, but I'll leave a comment here if I can get the flags working for the build scripts.

**Comment by ospfranco** [comment]
Ah, no they are not global variables.

https://www.sqlite.org/geopoly.html

In any case, no idea tbh. You will have to play around and see what works, try it on the CMakeLists cxx flags, maybe that will work.

**Comment by HaydenPWoods** [comment]
That's a shame (it would almost be too convenient..!). No worries, and thanks for the guidance - I'll close this issue for now whilst I look into it further, and I'll note it here if I have any success.

**Comment by ospfranco** [comment]
At least on iOS/macOS here is where I set additional compilation flags. In this case for Swift compilation. But you should be able to add further flags for CLang compilation.

<img width="1002" alt="Screenshot 000176" src="https://user-images.githubusercontent.com/1634213/162487219-ce2108b5-3df2-4c46-81c8-a3a293801d6d.png">

Best of luck trying to make it work.

**Comment by savv** [comment]
Enabling the various sqlite extensions seems like a common enough feature and part of what makes sqlite great to use.

Would it be worth reopening this and figuring out how to make it easy?

**Comment by ospfranco** [comment]
Have you tried changing the xcode settings I posted?

**Comment by savv** [comment]
Thanks, I am planning to try it in the next few days. What about Android?

For me, "making it easy" means that this is documented somewhere, which then also implies long term support.

**Comment by savv** [comment]
Hi Oscar, understood, I didn't mean to suggest that you need to work on it with any urgency (nor that it has to be you) - I was merely stating that we should keep this issue open because it's a useful one, as well as what I meant.

Regarding cmakelists, it's not obvious to me how to inject options there without forking the library and setting them inside of the forked version.

**Comment by ospfranco** [comment]
https://github.com/ds300/patch-package

**Comment by craftzdog** [comment]
Setting a flag in the Pod project works:

<img width="1165" alt="CleanShot 2022-09-28 at 16 01 42@2x" src="https://user-images.githubusercontent.com/1332805/192711304-29d62c7a-872f-4919-9eac-2ab9ab480d90.png">

But I don't know how to set it via `Podfile` in my project atm 🤔

**Comment by ospfranco** [comment]
I'm open to ideas on how to pass these flags without patch package to CMakeLists and Xcode. I didn't figure out a nice way to do it so far.

**Comment by craftzdog** [comment]
managed to change the build config via Podfile of the RN project by using a `post_install` hook!

```ruby
  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "react-native-quick-sqlite" then
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'SQLITE_ENABLE_FTS5=1']
        end
      end
    end
  end
```

Next up is CMakeLists

**Comment by craftzdog** [comment]
ok, adding the following lines to the CMakeLists.txt works!

```groovy
add_definitions(
  -DSQLITE_ENABLE_FTS5
)
```

well, how can this be specified from the parent project🤔 
Something like `rootProject.ext.get('quickSqliteBuildFlags')` in `build.gradle`?

**Comment by bessey** [comment]
I found this issue via Powersync's docs site. Cheers for your efforts @craftzdog!

For those looking to achieve this today its even simpler on Android than  https://github.com/ospfranco/react-native-quick-sqlite/issues/37#issuecomment-1261729930. Now you can just add `quickSqliteFlags="-DSQLITE_ENABLE_FTS5"` to your `gradle.properties`. See https://github.com/ospfranco/react-native-quick-sqlite/pull/86 for how this works.

**Comment by ospfranco** [comment]
You should move on to op-sqlite, I've added the capability of putting compilation flags in package.json
