### ISSUE TITLE
`openDatabase` API is not compatible with sqlite-2 or sqlite-storage

### ISSUE THREAD

**Issue by craftzdog** [ospfranco/react-native-quick-sqlite#39]
Hi Oscar,

The readme says it's compatible with those two libraries but looks like not.
The signature of `openDatabase` should be `openDatabase(name, version, description, size, onSuccess, onError)`
Is that intended?

It's not a big issue as it can be avoided by making a simple wrapper function.

**Comment by ospfranco** [comment]
Hi Takuya! Yeah, I think you are right, I actually made it compatible with TypeORM first, which in theory uses the now-defunct WebSQL specification. But like you said I can create a simple wrapper function.

I will take a look into it today (and also transactions)

**Comment by craftzdog** [comment]
Hold on, I'm working on making WebSQL wrapper module now :)

**Comment by craftzdog** [comment]
Published 🎉 https://github.com/craftzdog/react-native-quick-websql
