### ISSUE TITLE
Doubt: Close connections on Destroy

### ISSUE THREAD

**Issue by EduFrazao** [ospfranco/react-native-quick-sqlite#40]
Hi. I have a doubt: QuickSQLite should automatically close opened connections when the application gets detroyed?
As far as I know its not possible to react to this events from ReactNative JavaScript side, and its recommend to keep SQLite databases opened for the entire lifecicle of the application.
In this case, should this library hook native application destroy events to close this connections?

**Comment by ospfranco** [comment]
Not sure if I understand this correctly or if this is really an issue. If the application is killed then nothing is running, including SQLite (since it is embedded within the app process).

Did you do some testing and when/if you kill the app is there some dangling connection?

**Comment by EduFrazao** [comment]
> 

In fact I'm just wondering I must close the sqlite3* object in order to avoid any problem with database not flushing data or something like that. But i'm reading the SQLIte3 close method source, and looks like that SQLite does not even holds file handlers per connection. Looks like the database file is opened only during transactions. The close method only rollback running transactions and mark the current connection as a zombie if its busy.
I think that it is really harmless to not close a connection when the application is terminated, do you agree?

**Comment by ospfranco** [comment]
ah, you mean the app is killed and there is an ongoing transaction/operation. Well, none of the previous implementations did anything to handle this case, so it seems like too much of an edge case. So I think I would just ignore it for now until someone complains. It can also be handled in the user space by manually closing the connection with some hook on the react side or something.

**Comment by EduFrazao** [comment]
> 

I agree! Thanks for your answer.
