### ISSUE TITLE
Performance Metrics

### ISSUE THREAD

**Issue by gillpeacegood** [ospfranco/react-native-quick-sqlite#45]
It would help me to decide whether to migrate to this module if there was some performance comparison metrics with the other modules in the space (react-native-sqlite-storage for eg)

I don't doubt its faster though and its great work you've done

**Comment by ospfranco** [comment]
As stated, performance metrics are tricky and one can fall into micro benchmarking and effectively prove nothing, for example:

https://twitter.com/thymikee/status/1524692561671110659

As stated, the benefit of the JSI is very clear when transmitting large amounts of data between the native side and JS. How much will depend on each application.  I don't think it will help anyone to do bombastic claims. Just rest assured, it's faster than the old implementation
