### ISSUE TITLE
Enable JSON1 on Android

### ISSUE THREAD

**Issue by LaGregance** [ospfranco/react-native-quick-sqlite#46]
Hi,
Is there a way to enable JSON1 module for Android in order to use json_extract in SQL queries ?

This also can be a good point about the cross-platform compatibility since iOS manage it already.
Thanks for help.

**Comment by EduFrazao** [comment]
Hi. Its default enable on SQLite 3.38.x.
Did you have any problems?

**Comment by ospfranco** [comment]
@LaGregance please respond, otherwise I will just close the issue

**Comment by LaGregance** [comment]
Sorry for the delay. I've give up using this lib because I'm not able to use it with typeorm. We can close this issue.
FYI, I've found a way to use JSON1 & Typeorm with react-native-sqlite-storage :
https://stackoverflow.com/questions/72178612/making-typeorm-use-react-native-sqlite-2-on-react-native-to-use-json1

**Comment by ospfranco** [comment]
@EduFrazao it seems like people are really keen on compiling SQLite with all these extra extensions and plugins. Maybe there was a way for @LaGregance to make it work, but it seems useful to document the process of enabling plugins manually. Have you tried this yourself? Anyway to pass parameters when compiling SQLite?

**Comment by EduFrazao** [comment]
Hi @ospfranco . The only extension I need today is JSON1, and its default enabled on SQLite 3.38.x. I'm using it right now. But let me try this weekend with another extensions.

On Android I belive that this can be done passing custom cmake arguments: https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/dsl/ExternalNativeCmakeOptions

But I need to check how to this with IOS too.

**Comment by ospfranco** [comment]
So JSON1 is working on Android? weird... but yeah, just documenting how to pass arguments would already be useful

**Comment by LaGregance** [comment]
> So JSON1 is working on Android? weird... but yeah, just documenting how to pass arguments would already be useful

I agree, I don't know where I need to pass these arguments too, especially in a react app.
But as I say in my previous post you can use JSON1 on android with react-native-sqlite-storage by editing you `react-native.config.js` (https://www.npmjs.com/package/react-native-sqlite-storage#user-content-how-to-use-android)

@EduFrazao For iOS it's seems the default SQLite version already load JSON1 (but still usefull to know how to manually add others extensions)

**Comment by EduFrazao** [comment]
> So JSON1 is working on Android? weird... but yeah, just documenting how to pass arguments would already be useful

Yes, tested on Android and IOS. This extension becomes default enabled since SQLite 3.38.0.

https://www.sqlite.org/releaselog/3_38_0.html

`
The JSON functions are now built-ins. It is no longer necessary to use the [-DSQLITE_ENABLE_JSON1](https://www.sqlite.org/compile.html#enable_json1) compile-time option to enable JSON support. JSON is on by default. Disable the JSON interface using the new [-DSQLITE_OMIT_JSON](https://www.sqlite.org/compile.html#omit_json) compile-time option.
`

**Comment by EduFrazao** [comment]
> > So JSON1 is working on Android? weird... but yeah, just documenting how to pass arguments would already be useful
> 
> I agree, I don't know where I need to pass these arguments too, especially in a react app. But as I say in my previous post you can use JSON1 on android with react-native-sqlite-storage by editing you `react-native.config.js` (https://www.npmjs.com/package/react-native-sqlite-storage#user-content-how-to-use-android)
> 
> @EduFrazao For iOS it's seems the default SQLite version already load JSON1 (but still usefull to know how to manually add others extensions)

What errors did you have using json_extract on Android?
I use this function in several querys here.

**Comment by LaGregance** [comment]
Yes I know, but as I said before I've finally used `react-native-sqlite-storage`, with this package you can chose to use the default SQLite bundle (without JSON1) or the bundle from the lib (more recent, with JSON1), in my case this solution is perfect (JSON1 + typeorm).
For some reason I was not able to use the Typeorm patch with `react-native-quick-slite` : incomprehensible error, differing from refresh to refresh... Since I found a solution for my case, I did not investigate further. Note that the version of the patch for typeorm is quite far from the last version (I had to downgrade typeorm to do my tests)

**Comment by EduFrazao** [comment]
> Yes I know, but as I said before I've finally used `react-native-sqlite-storage`, with this package you can chose to use the default SQLite bundle (without JSON1) or the bundle from the lib (more recent, with JSON1), in my case this solution is perfect (JSON1 + typeorm). For some reason I was not able to use the Typeorm patch with `react-native-quick-slite` : incomprehensible error, differing from refresh to refresh... Since I found a solution for my case, I did not investigate further. Note that the version of the patch for typeorm is quite far from the last version (I had to downgrade typeorm to do my tests)

I understand. Thank you for your detailed answer.

@ospfranco Can I open a issue to upgrade the TypeORM patch to last version?

**Comment by ospfranco** [comment]
I'm thinking about what to do, the problem with the patch is that it will get out of sync every time. The patch is also very simple (replaces two strings) but I can already see people don't look inside of it. Ideally submitting a PR to TypeORM is the way to go, but I already tried it and they want tests to be added to each driver, but the codebase is huge and they take months to reply.

I think it might be better to just add some detailed instructions to users to create a patch themselves. As for the JSON1 issue, I want to give it a try myself.

**Comment by ospfranco** [comment]
Everything is working fine for me, so going to leave this issue closed and create another two, one for the TypeORM instructions and another for exploring the usage of the phone's embedded SQLite (really useful to keep binary size down).

<img width="1335" alt="Screenshot 000487" src="https://user-images.githubusercontent.com/1634213/168732243-f2f78c26-5bd8-4f13-bfe0-0701ff18e8be.png">
