### ISSUE TITLE
open fails with undefined location

### ISSUE THREAD

**Issue by aguycalled** [ospfranco/react-native-quick-sqlite#48]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-quick-sqlite@3.1.1` for the project I'm working on.

`location` is an optional parameter, but `sqlite.open` fails when `location` is undefined. This patch falls back to an empty string in that case.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-quick-sqlite/src/index.ts b/node_modules/react-native-quick-sqlite/src/index.ts
index 2892569..072247b 100644
--- a/node_modules/react-native-quick-sqlite/src/index.ts
+++ b/node_modules/react-native-quick-sqlite/src/index.ts
@@ -169,7 +169,7 @@ const enhanceQueryResult = (result: QueryResult): void => {
 
 const _open = sqlite.open;
 sqlite.open = (dbName: string, location?: string) => {
-  const res = _open(dbName, location);
+  const res = _open(dbName, location || '');
   if (res.status === 0) {
     locks[dbName] = {
       queue: [],
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ospfranco** [comment]
Thanks for noticing, I just published version 3.1.2 that fixes it on the native side
