### ISSUE TITLE
Not compatible with indexeddbshim

### ISSUE THREAD

**Issue by aguycalled** [ospfranco/react-native-quick-sqlite#49]
I'm not sure what is the standard way of doing it, but the current implementation is not compatible with `indexeddbshim`.

In order to make it work, `openDatabase` needs to return the connection:

```typescript
export const openDatabase = (
  options: IConnectionOptions,
  ok: (db: IDBConnection) => void,
  fail: (msg: string) => void
) => {
  try {
    sqlite.open(options.name, options.location);

    const connection: IDBConnection = {
        ...
    };

    ok(connection);

    return connection;
  } catch (e) {
    fail(e);
  }
};
```

**Comment by ospfranco** [comment]
I don't know what `indexeddbshim` is, this wrapper was meant for TypeORM, some people seem to like it more than the pure functions, but I wouldn't really recommend it.

It does look like you could solve this by just creating your own wrapper function?

**Comment by ospfranco** [comment]
Thought about this some more, I guess there is no harm in returning the object itself, if you open a PR I'll gladly merge it
