### ISSUE TITLE
Doesn't work with typeorm 0.3.0 and above

### ISSUE THREAD

**Issue by likern** [ospfranco/react-native-quick-sqlite#54]
It would be awesome to have such support!

**Comment by likern** [comment]
```
LOG  2022-05-31T15:24:07.479Z | ERROR : [useAccount:connectToDatabase] connection failed: {}; TypeError: Cannot read property 'length' of undefined

**Comment by likern** [comment]
This happens when I try to initialize database for the first time, I think it's inside `.initialize()` call.

![Снимок экрана от 2022-05-31 18-40-38](https://user-images.githubusercontent.com/842306/171214083-679905a9-8e91-4065-b6b8-8c60c2fa8adb.png)

When Hermes is on (doesn't show line where error happened)
```
 LOG  2022-05-31T15:24:07.479Z | ERROR : [useAccount:connectToDatabase] connection failed: {}; TypeError: Cannot read property 'length' of undefined 
```

When Hermes is off
```
 LOG  2022-05-31T15:28:15.431Z | ERROR : [useAccount:connectToDatabase] connection failed: {"line":348275,"column":58,"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.breeffy.feeve&modulesOnly=false&runModule=true"}; TypeError: undefined is not an object (evaluating 'result.length') 
```
Line where error is happened
![Снимок экрана от 2022-05-31 18-34-07](https://user-images.githubusercontent.com/842306/171213704-6ef671ba-4314-433d-83b6-3d9362583b1d.png)

I think it's related to this code in typeorm
![Снимок экрана от 2022-05-31 18-42-51](https://user-images.githubusercontent.com/842306/171214456-af7fda71-1ae5-4df2-bad8-cd6cea47c83a.png)

**Comment by likern** [comment]
This is my error I catch (which propogates errors from sqlite)
![Screenshot_2022-05-31-18-24-16-066_com breeffy feeve](https://user-images.githubusercontent.com/842306/171214922-d5a14f16-f1c1-4e16-a2d3-a1d620a40742.jpg)

**Comment by ospfranco** [comment]
From what I can see type ORM 0.3.x is a major change, I'm trying to get it to work from scratch but getting a slew of other errors, which I don't think have anything to do with this package. In any case, if you can provide a reproducible example that deals with a simple instantiation it would be better, because I don't understand your code from the small snippets that I see

**Comment by ospfranco** [comment]
It seems the warning is harmless (somehow? still confusing)

The biggest problem seems to be TypeORM ReactNative driver fails to resolve some internal dependency... no idea why. Maybe the latest version makes it incompatible with yarn or metro

![Screenshot 000555](https://user-images.githubusercontent.com/1634213/171335323-1c8733a0-97c5-46d2-9372-39b471a61b5b.png)

**Comment by ospfranco** [comment]
Seems TypeORM now always require some array result to be there even if the query has failed.

I've published a new version (3.1.7) can you check if it fixes the issue for you? I updated the example project and there it is working fine.

**Comment by likern** [comment]
Thanks! I've tested and it works. No more this error. Other app functionality seems work.

**Comment by ospfranco** [comment]
nice!
