### ISSUE TITLE
Avoid global scope

### ISSUE THREAD

**Issue by alpha0010** [ospfranco/react-native-quick-sqlite#59]
The term `sqlite` is sufficiently common as to be inconvenient (for me) to be taken globally.  It would be nice if I could `import {sqlite as myOtherSqlite} from 'react-native-quick-sqlite';`.

Potentially register global object (that is what you need for JSI, yes?) as `rnQuickSqlite`, which no one else is likely to use, and `export const sqlite = rnQuickSqlite;` for named imports from this lib.

**Comment by ospfranco** [comment]
Why exactly is inconvenient for you? can you paste some sample code?

**Comment by ospfranco** [comment]
You can also move the object to w/e you want, it doesn't need to be tied to the global scope, something like the following might work:

```
export const sqlite = sqlite
delete global.sqlite
```

**Comment by alpha0010** [comment]
2. Code review tends to be done through web interface, so vscode (or similar) is not available.

Thanks; I suppose unless you are also making other breaking changes, it does not really make sense to change API just for this. Well, up to you if you decide to change entry point in the future.

**Comment by savv** [comment]
For what it's worth, I also found the global scope a bit awkward...
I would have expected sqlite.open() to return a class, with methods like executeSql. This object should internally then just pass the db name to the JSI methods, rather than exposing this detail to the user.

[sql-js](https://github.com/sql-js/sql.js/)'s Api would be a good one to copy. I have done something similar for our DB API here, [react-native-leveldb](https://github.com/greentriangle/react-native-leveldb), happy to provide more context if helpful.

**Comment by ospfranco** [comment]
`open` does not return an object, but openDb which was meant to be used by TypeORM, I can see however this is causing issues for you. I'll try to refactor it, but I'm short on time at the moment, PRs are welcome.

**Comment by savv** [comment]
I see, I had missed that function. That is what I meant, thanks.

**Comment by ospfranco** [comment]
that is not because of the global scope, but some other issue with the module initialization, I haven't been able to figure out why.

**Comment by ospfranco** [comment]
Going to re-open this, I'm in the process of doing a big refactor and might as well take out the bindings from the global scope

**Comment by ospfranco** [comment]
only with a reproducible example, I haven't been able to isolate it

**Comment by savv** [comment]
> The fact that it's in the global scope seems to sometimes also cause crashes, e.g.:
> 
> ```
> RCTFatalException: Unhandled JS Exception: ReferenceError: Can't find variable: sqlite: Unhandled JS Exception: ReferenceError: Can't find variable: sqlite, stack:
> <unknown>@11:351
> h@2:1585
> <unknown>@6:46
> h@2:1585
> d@2:958
> global code@1964:3
> ```
> 
> That said, I don't fully understand why. I `import 'react-native-quick-sqlite';` in index.js, which installs the module / creates sqlite

These seem to always happen when codepush installs its update (but not always!).

**Comment by savv** [comment]
> the latest update already takes care of the global variable, have you already updated and does it still present issues?

I haven't yet; do you expect that it would help? I couldn't see why after looking at the changes since 3.18. I will upgrade in the next month, and report back with the results.
