### ISSUE TITLE
TypeORM swallows up errors

### ISSUE THREAD

**Issue by amhed** [ospfranco/react-native-quick-sqlite#61]
Behavior: 
Using react-native-quick-sqlite as the driver for TypeORM swallows up errors and return an empty array instead

Expectation:
TypeORM should throw. Like it does with the default `react-native-sqlite-storage` implementation

Here's a quick repo that setups up the behavior
https://github.com/amhed/quick_typeorm_bug/blob/master/App.tsx

**Comment by ospfranco** [comment]
Thanks for opening the issue, there is already a fix committed to main (in case you need to pull urgently). But I'm actually going to make a big refactor, but I need some time to get it done.

**Comment by ospfranco** [comment]
@amhed did you check the fix on main? do you have the same change or did you apply any other changes?

**Comment by amhed** [comment]
Lemme check

**Comment by amhed** [comment]
Yup! https://github.com/ospfranco/react-native-quick-sqlite/commit/e8b4f42cbdae4370b26a0c457390dbb7c31607ac is pretty similar to the patch we applied. Thanks for that

Will update instead of patching once 3.1.9 is out. Thanks again @ospfranco

**Comment by ospfranco** [comment]
Will be released under 4.0.0, bare in mind I changed how the bindings are installed, they are still on a global object, but you are not supposed to access it directly, but rather `import {QuickSQLite} from 'react-native-quick-sqlite'`
