### ISSUE TITLE
Build failed because of '/node_modules/react-native/android' more than one .aar files (Hermes & react-native)

### ISSUE THREAD

**Issue by danielhj1998** [ospfranco/react-native-quick-sqlite#63]
Hello, my project uses API level 31 with RN 0.69.1

```gradle
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
```

When trying to build I get the following error:

```gradle
* Where:
Build file '$root/node_modules/react-native-quick-sqlite/android/build.gradle' line: 183

* What went wrong:
A problem occurred evaluating project ':react-native-quick-sqlite'.
> Expected directory '$root/node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.
```

The 183 line in the '$root/node_modules/react-native-quick-sqlite/android/build.gradle' is:

```gradle
def rnAAR = fileTree("${nodeModules}/react-native/android").matching({ it.include "**/**/*.aar"}).singleFile
```

I think this happens because in the '$root/node_modules/react-native/android/com/facebook/react/' directory there are the 'react-native' and 'hermes-engine' directories which contain a `.aar` file.

Could you help me solve this problem? Thanks in advance

**Comment by craftzdog** [comment]
Maybe it could solve this: https://github.com/mrousavy/react-native-vision-camera/pull/1116

**Comment by ospfranco** [comment]
That is precisely what I needed, thanks @craftzdog!

@danielhj1998 @Fagner3g the main branch is patched, can you try it and let me know if it works for you? afterward, I will publish it to npm
