### ISSUE TITLE
Database files are installed in odd location

### ISSUE THREAD

**Issue by robinsoncol** [ospfranco/react-native-quick-sqlite#68]
Hello, I noticed that react-native-quick-sqlite installs database files under `/data/data/<app-name>/files/databases` when I call `QuickSQLite.open('myDatabase', 'databases')`. Is this behavior expected? The general consensus is that database files should live under `/data/data/<app-name>/databases`.

I experienced this behavior both on a physical Android device and in a virtual device.

**Comment by ospfranco** [comment]
I didn't take a look into which location is "recommended" by android, I just took the document path:

https://github.com/ospfranco/react-native-quick-sqlite/blob/main/android/src/main/java/com/reactnativequicksqlite/QuickSQLiteBridge.java#L16

At this point I will not change it, to prevent apps already using the package from breaking, seems minor point to me, if you want to put it in the `<app-name>/databases` folder, just use `open('myDatabase', '../databases')`.
