### ISSUE TITLE
After upgrade to react-native-quick-sqlite queries stopped working

### ISSUE THREAD

**Issue by likern** [ospfranco/react-native-quick-sqlite#7]
After upgrading to `react-native-quick-sqlite` my queries stopped working. I think the reason is similar to https://github.com/typeorm/typeorm/issues/5564.
I'm investigating error.

https://user-images.githubusercontent.com/842306/130624876-633907e4-edb0-43bb-aa95-ebcd22d63986.mp4

**Comment by ospfranco** [comment]
This is a problem with TypeORM and not with this library, I just take whatever javascript is sent, cast/convert to the correct C++ type and pass it to SQLite

https://github.com/ospfranco/react-native-quick-sqlite/blob/main/cpp/sequel.cpp#L198
