### ISSUE TITLE
Swapping out react-native-sqlite2 causes data to disappear

### ISSUE THREAD

**Issue by Daniyaalbeg** [ospfranco/react-native-quick-sqlite#72]
Hi There,

Love the package and props for the awesome work!

I am just having some trouble. I have an app using react-native-sqlite2. I am using pouchdb. I swapped out react-native-sqlite2 with react-native-quick-sqlite, and used the adapter:

[react-native-quick-websql](https://github.com/craftzdog/react-native-quick-websql)

When I swapped it out (with no other change in my code) my data was not there, it seemed to be using a new SQL Db. Changing back to react-native-sqlite2 restored all my data. So my guess is somewhere it is creating a new DB instead of connecting to the old one, perhaps because of a name change?

Honestly not sure, and wanted to see if anyone might have any idea what may be the cause of this? Would it be this package, or perhaps react-native-quick-websql doing something when calling the open function for this package?

Any help to get pointed in the right direction would be appreciated.

**Comment by ospfranco** [comment]
Refer to https://github.com/ospfranco/react-native-quick-sqlite/issues/66

The base paths taken by sqlite-2 and quick-sqlite are different, you need to point quick-sqlite to the correct location of your db

**Comment by Daniyaalbeg** [comment]
Perfect, just the clarification I needed! Thanks a lot 😄
