### ISSUE TITLE
Flipper Database support on iOS

### ISSUE THREAD

**Issue by chrisdrackett** [ospfranco/react-native-quick-sqlite#74]
This isn't really an issue but more of an FYI. I made a driver for https://codeberg.org/panz3r/react-native-flipper-databases that can be used to add Flipper Database support for this package on iOS. This was pretty quick code, but it works for me and might help someone else who wants to do the same.

Here is the PR with the relevant code: https://codeberg.org/panz3r/react-native-flipper-databases/pulls/2

**Comment by ospfranco** [comment]
I only see 404

**Comment by chrisdrackett** [comment]
yeah, seems like you need to make an account to be able to even see the repo :\

*sigh*

**Comment by chrisdrackett** [comment]
looks like my PR got merged, you can see usage in the docs here: https://www.npmjs.com/package/react-native-flipper-databases

**Comment by ospfranco** [comment]
Ah, now I get it... you don't need any change on this package, but you added functionality to that package to explore quick-sqlite databases. That's very useful though! You can submit a PR modifying the readme, I'm sure a lot of people will need it sooner or later :)
