### ISSUE TITLE
SQLite compression extension support

### ISSUE THREAD

**Issue by mr-tm** [ospfranco/react-native-quick-sqlite#85]
Given the fact that this library has option to ship with its own SQLite and it is meant for quickly querying large datasets, would it be possible to add support for SQLite compression extension?

I've found some Open Source SQLite compression extensions:
https://github.com/phiresky/sqlite-zstd#cross-compiling
https://github.com/mlin/sqlite_zstd_vfs
Can be built as a static library, already tested on iOS, macOS:
https://github.com/techrah/sqlite3-compression-encryption-vfs (best option?)

This could greatly benefit users due to reduced storage space needed for apps with large SQLite databases.

**Comment by ospfranco** [comment]
The readme of the project states that it is not ready for production. Also, modifying the compilation process cannot be easily achieved. IMO it is out of the scope of this project and you might want to create your own fork. Closing this.
