### ISSUE TITLE
Setting location to match react-native-sqlite-storage

### ISSUE THREAD

**Issue by zzorba** [ospfranco/react-native-quick-sqlite#9]
i'm trying to move from `react-native-sqlite-storage` to this library, and have run into an issue with trying to get the system to open the existing sqlite database.

I'm using typeorm with the 'default' location, but I believe `react-native-sqlite-storage` controls the database location.

i've managed to locate the database 'location' on android ("../databases"), however I can't figure out who to match the location on iOS.

My database (named arkham4) lives in this folder on my local simulator
`/Users/****/Library/Developer/CoreSimulator/Devices/13FEAA10-6E19-462A-B297-01551B61E6DE/data/Containers/Data/Application/1013B249-C233-4756-93B1-9FE741E17560/Library/LocalDatabase`

Any advice on how to achieve backwards compatibility?  I could recreate the database, but would rather not orphan the old data / force a large reload if I can avoid it.

**Comment by ospfranco** [comment]
Hey, yes, indeed, the default location for the databases is on the `databases` folder in the user directory, you can however navigate out of this directory by modifying the path you pass when initializing the connection:

```
sqlite.open('myDatabase', '../LocalDatabase');
```
