### ISSUE TITLE
Unable to open database when using The New Architecture

### ISSUE THREAD

**Issue by cmoel** [ospfranco/react-native-quick-sqlite#90]
👋 Thanks for this library. The recent improvements for promise-based transactions look great.

I generated a new app using the `react-native-template-typescript` template. After adding `react-native-quick-sqlite` and installing using the instructions under [The New Architecture](https://reactnative.dev/docs/the-new-architecture/use-app-template#enable-the-new-architecture) (I'm currently focused on iOS and haven't tried Android), I get an error when calling the `open` function:

<img width="439" alt="Screen Shot 2022-10-08 at 21 40 28" src="https://user-images.githubusercontent.com/272904/194733582-021d11d6-7668-4fbb-b9a7-58b65d141e73.png">

The odd thing about this error is I'm passing a string to `open`:

```typescript
import { open } from 'react-native-quick-sqlite'
let result = open("main.sqlite")
```

Is it possible to use react-native-quick-sqlite with [The New Architecture](https://reactnative.dev/docs/the-new-architecture/landing-page)?

**Comment by ospfranco** [comment]
This has nothing to do under the fabric or any of the other mumbo jumbo, JSI bindings should always work. You seem to be importing the wrong function though, did you check you are on the latest version (5.0.1)?

**Comment by cmoel** [comment]
Yes, I'm using version 5.0.1. It sounds like I'm doing something wrong, so I'm happy to close this.

**Comment by ospfranco** [comment]
Somehow you are importing this:

<img width="520" alt="Screenshot 001113" src="https://user-images.githubusercontent.com/1634213/194834290-a4f1f623-e9f6-484d-b30a-27eeec079f4b.png">

Whereas you should be importing this:

<img width="582" alt="Screenshot 001114" src="https://user-images.githubusercontent.com/1634213/194834338-a1429a08-6573-4ec1-8026-b2a522a37d92.png">

Check your TSConfig, maybe syntethicDefaultImports causes an issue or some other problem, but you should not be able to destructure the internal properties of the QuickSQLite object mentioned in the README

**Comment by cmoel** [comment]
Cool, thanks for your help @ospfranco!
