### ISSUE TITLE
Foreign key constrain failure results in DB lock

### ISSUE THREAD

**Issue by vishalnarkhede** [ospfranco/react-native-quick-sqlite#96]
I am using v4 of `react-native-quick-sqlite` package. While using `sqlite.executeSqlBatch` operation, if one of the foreign key constrains fails, then DB is left in locked state forever until I reopen the app. Is there a good way of avoiding this or whats the best way of handling this failure?

**Comment by ospfranco** [comment]
@EduFrazao is the C++ code of executeSqlBatch catching exceptions/errors correctly?

**Comment by EduFrazao** [comment]
> @EduFrazao is the C++ code of executeSqlBatch catching exceptions/errors correctly?

Hi @ospfranco and @vishalnarkhede .
I belive that there is a missing rollback in case of SQL erros in during the batch execution.
The batch execution uses a exclusive transaction, and in case of SQLErrors, the routine only quits.
I've made a PR (#97)  to invoke a rollback before returning with the SQL error.

**Comment by vishalnarkhede** [comment]
Thanks for the PR @EduFrazao . I will try the updated version and get back

**Comment by EduFrazao** [comment]
> Thanks for the PR @EduFrazao . I will try the updated version and get back

Nice! Please let me know the results!

**Comment by ospfranco** [comment]
The catch should now solve any pending transaction. I'm closing this, but feel free to tell us if it is not working and I will re-open it.
