### ISSUE TITLE
How to use Quick SQLite in a unit test ?

### ISSUE THREAD

**Issue by ducdetronquito** [ospfranco/react-native-quick-sqlite#98]
Hi !

First, thank you for developing Quick SQLite, it looks very clean :)

My question may be silly as I'm pretty new to React-Native, but how do you run a unit test of a function that uses Quick SQLite ?

Say that in an application, you have the following function:

```ts
function getUserCount(): number {
    const db = open({name: "users.db"});
    let { rows } = db.execute('SELECT COUNT(*) as userCount FROM users;');
    return rows?.item(0)["userCount"];
    db.close();
}
```

I would like to unit test this function an run it with Jest on my computer, to ensure it keep behaving as expected.
We can have a unit test files like the following:

```ts
test('Has no users in DB', () => {
    expect(getUserCount()).toBe(0);
});
```

As of yet, this unit test will fail to run with the following error:

```
Base quick-sqlite module not found. Maybe try rebuilding the app.

> 1 | import { open } from 'react-native-quick-sqlite';

at Object.<anonymous> (node_modules/react-native-quick-sqlite/lib/commonjs/index.ts:12:11)
at Object.<anonymous> (__tests__/sqlite.test.ts:1:1)
```

Do you have any hints on how I could make this kind of unit tests possible ?

Thanks in advance, and have a great day 🌴

**Comment by ospfranco** [comment]
you can't, this is a JSI module that depends on JSC/Hermes and therefore will only run on the React Native environment. You can write some pseudo test code when running in an app.

**Comment by ducdetronquito** [comment]
Ok, thanks for your quick answer !
